require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

# Tuya SDK pod sources
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TuyaInc/TuyaPublicSpecs.git'
source 'https://github.com/tuya/tuya-pod-specs.git'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityBarcodeScanner', :path => '../../node_modules/@capacitor-community/barcode-scanner'
end

def tuya_pods
  # ThingSmartCryption from local extracted SDK (must be first)
  pod 'ThingSmartCryption', :path => '../../iOS_SDK-2'
  
  # Core Tuya SDK pods for provisioning
  pod 'ThingSmartActivatorBizBundle', '~> 6.11.0'
  pod 'ThingSmartHomeKit', '~> 6.11.0'
  # Note: ThingSmartUserKit is not available as a separate pod
  # ThingSmartUser is likely included in ThingSmartHomeKit
  # If login fails, we may need to check the SDK documentation or use a different approach
end

def midea_pods
  # Midea MSmartSDK - using local SDK from MideaSDK directory
  # Note: SDK path is relative to Podfile location (ios/App/)
  # Path: ios/App -> ../ -> ios/ -> MideaSDK/OEMSDK/
  midea_framework_path = '../MideaSDK/OEMSDK/OEMPods_Framework'
  midea_source_path = '../MideaSDK/OEMSDK/OEMPods_Source'
  
  # Dependencies from OEMPods_Source (required by OEMBusiness)
  pod 'OEMLogger', :path => "#{midea_source_path}/OEMLogger"
  pod 'DolphinRouter', :path => "#{midea_source_path}/Dolphinrouter"
  # OEMEnvirement is required by OEMBusiness (contains OEMEnvConfig and OEMEnvirementManager)
  pod 'OEMEnvirement', :path => "#{midea_source_path}/OEMEnvirement"
  # Note: OEMTheme may be needed if OEMBusiness Core subspec is used
  # Uncomment if needed:
  # pod 'OEMTheme', :path => "#{midea_source_path}/OEMTheme"
  
  # Main Midea SDK pods from OEMPods_Framework
  pod 'OEMFoundation/NetworkFramework', :path => midea_framework_path
  pod 'OEMBusiness/NetworkFramework', :path => midea_framework_path
  # Note: MSmartSDK functionality is provided by OEMBusiness and OEMFoundation
  # Removed MSmartSDK pod reference to avoid MSSecretSDK framework not found error
end

target 'App' do
  capacitor_pods
  tuya_pods
  midea_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
  
  # Fix CocoaPods "[CP] Copy XCFrameworks" warnings
  # Add output dependencies to script phases to prevent running on every build
  installer.pods_project.targets.each do |target|
    target.build_phases.each do |phase|
      if phase.is_a?(Xcodeproj::Project::Object::PBXShellScriptBuildPhase) && phase.name == '[CP] Copy XCFrameworks'
        # Add output files to the script phase to fix warnings
        # This tells Xcode when the script actually needs to run
        phase.output_paths = [
          "$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/#{target.name}.framework"
        ].compact
      end
    end
  end
end
