require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

# Tuya SDK pod sources
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TuyaInc/TuyaPublicSpecs.git'
source 'https://github.com/tuya/tuya-pod-specs.git'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityBarcodeScanner', :path => '../../node_modules/@capacitor-community/barcode-scanner'
end

def tuya_pods
  # ThingSmartCryption from local extracted SDK (must be first)
  pod 'ThingSmartCryption', :path => '../../iOS_SDK-2'
  
  # Core Tuya SDK pods for provisioning
  pod 'ThingSmartActivatorBizBundle', '~> 6.11.0'
  pod 'ThingSmartHomeKit', '~> 6.11.0'
  # Note: ThingSmartUserKit may be included in ThingSmartHomeKit
  # If login fails, we may need to add it separately or use a different approach
end

target 'App' do
  capacitor_pods
  tuya_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
